name: matrix
on: push

jobs:
  get-matrix:
    strategy:
      matrix:
        version: [12,14]
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: check matrix
      run: |
        echo ${{ matrix.os }}
        echo ${{ matrix.version }}